### ISSUE TITLE
Rewrite blueberry using BFF

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/ui#42]
- [x] Changing input
- [x] Setting volume & mute
- [x] Audio control page
- [x] Projector screen control page
- [x] Mobile control page & features
- [ ] Sharing page & functionality
- [x] Help Request page*
- [x] Power state of the room

**Comment by jpw547** [comment]
I think projector screens need to be some kind of id and name pair on the control group, because I think the backend needs to know things like "SCR1" for example, but we would actually want to show the name "Projector Screen" or whatever on the touchpanel.

**Comment by jpw547** [comment]
Mobile control page architecture is done, but needs to actually get the control key properly.
Help request page architecture is done, but it is hard coded and the overall configurability of support information is contained in another issue.

**Comment by jpw547** [comment]
Now gets control key properly
